# Generated by Django 3.0.3 on 2020-04-26 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='opinion',
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.TextField(),
        ),
    ]
