# Generated by Django 3.0.3 on 2020-04-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200426_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
