# Generated by Django 3.0.3 on 2020-05-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='upi',
        ),
        migrations.AddField(
            model_name='payment',
            name='UPI',
            field=models.CharField(default=False, max_length=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay',
            field=models.CharField(choices=[('card', 'card'), ('online', 'online')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
