# Generated by Django 3.0.3 on 2020-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200501_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='UPI',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
