# Generated by Django 3.0.3 on 2020-05-22 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0006_auto_20200519_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='place_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.Places'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.CharField(choices=[('-------', '-------'), ('card', 'card'), ('online', 'online')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='no_of_people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
